-- UserDetail & UserBasic

--```sql
CREATE TABLE UserDetail (
	JOIN_SOC_NUM	VARCHAR2(20)	NOT NULL,
	JOIN_NAME	VARCHAR2(30)	NOT NULL,
	JOIN_PW	VARCHAR2(30)	NOT NULL,
	JOIN_GEN	VARCHAR2(5)	NOT NULL,
	JOIN_EMAIL	VARCHAR2(50)	NOT NULL,
	JOIN_PHONE	VARCHAR2(20)	NOT NULL,
	JOIN_ADDR_BASIC	VARCHAR2(100)	NOT NULL,
	JOIN_ADDR_DETAIL	VARCHAR2(100)	NOT NULL,
	JOIN_DATE	DATE DEFAULT SYSDATE	NOT NULL,
	JOIN_RIGHT	VARCHAR2(1)	NOT NULL
);

INSERT INTO UserDetail
VALUES ('1','홍길동','1234567ABC1','남','qwert@naver.com','010-1234-5678','강남구','에스코 빌딩4층',sysdate,'1');

ALTER TABLE UserDetail ADD CONSTRAINT PK_USERDETAIL PRIMARY KEY (
JOIN_SOC_NUM
);

CREATE TABLE UserBasic (
JOIN_ID	VARCHAR2(20)	NOT NULL,
JOIN_SOC_NUM	VARCHAR2(20)	NOT NULL,
ANM_NO_SEQ	NUMBER(10)	NOT NULL,
JOIN_PERSON	VARCHAR2(2) DEFAULT 0	NOT NULL	
);

ALTER TABLE UserBasic ADD CONSTRAINT PK_USERBASIC PRIMARY KEY (
JOIN_ID
);

ALTER TABLE UserBasic ADD CONSTRAINT FK_UserDetail_TO_UserBasic_1 FOREIGN KEY (
JOIN_SOC_NUM
)
REFERENCES UserDetail (
JOIN_SOC_NUM
);
--```

-- Slctn (UserBasic과 의존관계)

--```sql
CREATE TABLE Slctn (
SEL_NUM_SEQ	NUMBER(10)	NOT NULL,
SEL_NAME	VARCHAR2(10)	NOT NULL,
SEL_SUBCAT	VARCHAR2(10)	NOT NULL,
SEL_SCORE	NUMBER(10)	NOT NULL,
JOIN_ID	VARCHAR2(20)	NOT NULL
);

ALTER TABLE Slctn ADD CONSTRAINT PK_SLCTN PRIMARY KEY (
SEL_NUM_SEQ
);

ALTER TABLE Slctn ADD CONSTRAINT FK_UserBasic_TO_Slctn_1 FOREIGN KEY (
JOIN_ID
)
REFERENCES UserBasic (
JOIN_ID
);

CREATE SEQUENCE SEL_NUM_SEQ_NAME
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;

--```

-- TotalApplier (UserBasic과 의존관계)

--```sql
CREATE TABLE TotalApplier (
APP_NUM_SEQ	NUMBER(10)	NOT NULL,
JOIN_ID	VARCHAR2(20)	NOT NULL,
APP_WHTR_INGB	VARCHAR2(2)	NOT NULL,
APP_DATE	DATE DEFAULT SYSDATE NOT NULL,
APP_CLASSIFICATION	VARCHAR(10)	NOT NULL
);

ALTER TABLE TotalApplier ADD CONSTRAINT PK_TOTALAPPLIER PRIMARY KEY (
APP_NUM_SEQ,
JOIN_ID
);

ALTER TABLE TotalApplier ADD CONSTRAINT FK_UserBasic_TO_TotalApplier_1 FOREIGN KEY (
JOIN_ID 
)
REFERENCES UserBasic (
JOIN_ID
);

CREATE SEQUENCE APP_NUM_SEQ_NAME
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;

--```

-- Unqualify (UserBasic과 의존관계)

--```sql
CREATE TABLE Unqualify (
JOIN_ID	VARCHAR2(20)	NOT NULL,
UNQ_REASON	VARCHAR2(500)	NOT NULL
);

ALTER TABLE Unqualify ADD CONSTRAINT PK_UNQUALIFY PRIMARY KEY (
JOIN_ID
);

ALTER TABLE Unqualify ADD CONSTRAINT FK_UserBasic_TO_Unqualify_1 FOREIGN KEY (
JOIN_ID
)
REFERENCES UserBasic (
JOIN_ID
);
--```

-- Ins (UserDetail과 의존관계)

--```sql
------------------- Ins ----------------------

CREATE TABLE Ins (
INS_NUM	NUMBER(30)	NOT NULL,
INS_NAME	VARCHAR(30)	NOT NULL,
INS_PHONE	VARCHAR(30)	NOT NULL,
INS_FAXNUM	VARCHAR(30)	NOT NULL,
INS_ADDR	VARCHAR(50)	NOT NULL,
INS_ADDR_DETAIL	VARCHAR(50)	NOT NULL,
INS_RGSTR	DATE DEFAULT sysdate	NOT NULL,
INS_RLS	DATE	NULL,
JOIN_ID	VARCHAR(255)	NOT NULL
);
-- INS_RGSTR null로 들어가면 안되고 insert 시 sysdate를 지정, INS_RLS는 업데이트를 통해 값을 입력해야하기 때문에 null 허용 

ALTER TABLE Ins ADD CONSTRAINT PK_INS PRIMARY KEY (
INS_NUM
);

ALTER TABLE Ins ADD CONSTRAINT FK_UserBasic_TO_Ins_1 FOREIGN KEY (
JOIN_ID
)
REFERENCES UserBasic (
JOIN_ID
);
--```

-- FAQ(UserBasic과 의존관계)

--```sql
------------------- FAQ ----------------------

CREATE TABLE FAQ (
FAQ_NUMBER_SEQ	NUMBER(10)	NOT NULL,
FAQ_TITLE	VARCHAR2(50)	NOT NULL,
FAQ_CONTENT	VARCHAR2(1000)	NOT NULL,
FAQ_DATE	DATE	DEFAULT sysdate NOT NULL,
FAQ_HIT	NUMBER(5)	NOT NULL,
JOIN_ID	VARCHAR2(20)	NOT NULL
);

ALTER TABLE FAQ ADD CONSTRAINT PK_FAQ PRIMARY KEY (
FAQ_NUMBER_SEQ
);

ALTER TABLE FAQ ADD CONSTRAINT FK_UserBasic_TO_FAQ_1 FOREIGN KEY (
JOIN_ID
)
REFERENCES UserBasic (
JOIN_ID
);

CREATE SEQUENCE FAQ_NUMBER_SEQ_NAME
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;
--```

-- ANSWER(FAQ, MNGR과 의존관계)

--```sql
--------------------- ANSWER ------------------------


 CREATE TABLE ANSWER (
ANS_NUMBER_SEQ	NUMBER(10)	NOT NULL,
FAQ_NUMBER_SEQ	NUMBER(10)	NOT NULL,
MNGR_ID	VARCHAR(20)	NOT NULL,
ANS_WRITER	VARCHAR2(20)	NOT NULL,
ANS_CONTENT	VARCHAR2(1000)	NOT NULL,
ANS_DATE	DATE DEFAULT sysdate NOT NULL
);

-- 답변 번호 sequence

CREATE SEQUENCE ANS_NUMBER_SEQ_NAME
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;

ALTER TABLE ANSWER ADD CONSTRAINT PK_ANSWER PRIMARY KEY (
ANS_NUMBER_SEQ,
FAQ_NUMBER_SEQ,
MNGR_ID
);    

ALTER TABLE ANSWER ADD CONSTRAINT FK_FAQ_TO_ANSWER_1 FOREIGN KEY (
FAQ_NUMBER_SEQ
)
REFERENCES FAQ (
FAQ_NUMBER_SEQ
);

ALTER TABLE ANSWER ADD CONSTRAINT FK_Mngr_TO_ANSWER_1 FOREIGN KEY (
MNGR_ID
)
REFERENCES Mngr (
MNGR_ID
);
--```

-- Notice (Mngr과 의존관계)

--```sql
------------------------- 공지사항 ----------------------------
CREATE TABLE Notice (
NOTICE_NUMBER_SEQ	NUMBER(10)	NOT NULL,
MNGR_ID	VARCHAR(20)	NOT NULL,
NOTICE_TITLE	VARCHAR2(50)	NOT NULL,
NOTICE_WRITER	VARCHAR2(20)	DEFAULT 'ADMIN' NOT NULL,
NOTICE_CONTENT	VARCHAR2(3000)	NOT NULL,
NOTICE_DATE	DATE	DEFAULT sysdate NOT NULL,
NOTICE_FILES	VARCHAR2(50)	NOT NULL,
NOTICE_HITS	VARCHAR2(10)	DEFAULT '0' NOT NULL	
);

CREATE SEQUENCE NOTICE_NUMBER_SEQ_NAME
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;
    
ALTER TABLE Notice ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
NOTICE_NUMBER_SEQ,
MNGR_ID
);    

ALTER TABLE Notice ADD CONSTRAINT FK_Mngr_TO_Notice_1 FOREIGN KEY (
MNGR_ID
)
REFERENCES Mngr (
MNGR_ID
);
--```

-- RatingCriteria(UserBasic과 의존관계)

--```sql

CREATE TABLE RatingCriteria (
RC_NUM_SEQ	NUMBER(10)	NOT NULL,
RC_APC_NAME	VARCHAR2(50)	NOT NULL,
RC_TOTAL_CAREER	VARCHAR2(20)	NULL,
RC_LOCAL_CAREER	VARCHAR2(20)	NULL,
RC_OFFICE_LOCA	VARCHAR2(50)	NOT NULL,
RC_PERSONALY_EVALUATION	VARCHAR2(10)	NOT NULL,
RC_INTERVIEW_EVALUATION	VARCHAR2(10)	NOT NULL,
RC_CERITIFICATION_NAME1	VARCHAR2(30)	NULL,
RC_CERITIFICATION_NAME2	VARCHAR2(30)	NULL,
RC_CERITIFICATION_NAME3	VARCHAR2(30)	NULL,
RC_CERITIFICATION_NAME4	VARCHAR2(30)	NULL,
RC_TOTAL_SCORE	NUMBER	NOT NULL,
RC_APPRAISER_SCORE	NUMBER	NOT NULL,
RC_AJM_JDGE_SCORE	NUMBER	 DEFAULT 0 NULL,
RC_LAST_TOTAL_SCORE	NUMBER	NOT NULL,
JOIN_ID	VARCHAR(255)	NOT NULL
);

CREATE SEQUENCE RC_NUM_SEQ_NAME
    START WITH 1
    INCREMENT BY 1  
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;

ALTER TABLE RatingCriteria ADD CONSTRAINT PK_RATINGCRITERIA PRIMARY KEY (
RC_NUM_SEQ
);

ALTER TABLE RatingCriteria ADD CONSTRAINT FK_UserBasic_TO_RatingCriteria_1 FOREIGN KEY (
JOIN_ID
)
REFERENCES UserBasic (
JOIN_ID
);

-- commit;
--```

-- TS(TotalApplier와 의존관계)

--```sql
------------------ Ts --------------------------

CREATE TABLE Ts (
TS_NUM_SEQ	NUMBER(10)	NOT NULL,
TS_NAME	VARCHAR2(30)	NOT NULL,
TS_SOC_NUM	VARCHAR2(20)	NOT NULL,
TS_HOME_NUM	VARCHAR2(20)	NULL,
TS_ACAD_BACK	VARCHAR2(500)	NOT NULL,
TS_ACAD_BACK_FILE	VARCHAR2(30)	NULL,
TS_CARRER	VARCHAR2(500)	NOT NULL,
TS_CARRER_FILE	VARCHAR2(30)	NOT NULL,
TS_EMAIL	VARCHAR2(50)	NOT NULL,
TS_PHONE_NUM	VARCHAR2(20)	NOT NULL,
TS_BANK	VARCHAR2(20)	NOT NULL,
TS_ACC_HOL	VARCHAR2(30)	NOT NULL,
TS_BANK_NUM	VARCHAR2(30)	NOT NULL,
TS_POST_NUM	VARCHAR2(10)	NOT NULL,
TS_ADDR	VARCHAR2(100)	NOT NULL,
TS_DTL_ADDR	VARCHAR2(100)	NOT NULL,
TS_EXPRT	VARCHAR2(50)	NOT NULL,
TS_LNGG	VARCHAR2(50)	NOT NULL,
TS_DSGNT_COURT	VARCHAR2(100)	NOT NULL,
TS_ACTVT_AREA	VARCHAR2(100)	NOT NULL,
APP_NUM_SEQ	NUMBER(10)	NOT NULL,
JOIN_ID	VARCHAR2(20)	NOT NULL
);

CREATE SEQUENCE TS_NUM_SEQ_NAME
    START WITH 1
    INCREMENT BY 1  
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;
    
ALTER TABLE Ts ADD CONSTRAINT PK_TS PRIMARY KEY (
TS_NUM_SEQ
);

ALTER TABLE Ts ADD CONSTRAINT FK_TotalApplier_TO_Ts_1 FOREIGN KEY (
APP_NUM_SEQ, JOIN_ID
)
REFERENCES TotalApplier (
APP_NUM_SEQ, JOIN_ID
);
--```

-- Gh(TotalApplier와 의존관계)

--```sql
CREATE TABLE Gh (
GH_NUM_SEQ	NUMBER(10)	NOT NULL,
GH_NAME	VARCHAR2(30)	NOT NULL,
GH_OFC_NAME	VARCHAR2(20)	NOT NULL,
GH_OFC_NUM	VARCHAR2(20)	NOT NULL,
GH_YEAR	VARCHAR2(20)	NOT NULL,
GH_SRTTN	VARCHAR2(1)	NOT NULL,
GH_SOC_NUM	VARCHAR2(20)	NOT NULL,
GH_BSNS_NUM	VARCHAR2(30)	NOT NULL,
GH_JOB	VARCHAR2(50)	NOT NULL,
GH_FAX	VARCHAR2(20)	NOT NULL,
GH_HOME_NUM	VARCHAR2(20)	NULL,
GH_ACAD_BACK	VARCHAR2(500)	NOT NULL,
GH_ACAD_BACK_FILE	VARCHAR2(30)	NOT NULL,
GH_CARRER	VARCHAR2(500)	NOT NULL,
GH_CARRER_FILE	VARCHAR2(30)	NOT NULL,
GH_EMAIL	VARCHAR2(50)	NOT NULL,
GH_PHONE_NUM	VARCHAR2(20)	NOT NULL,
GH_BANK	VARCHAR2(20)	NOT NULL,
GH_ACC_HOL	VARCHAR2(30)	NOT NULL,
GH_BANK_NUM	VARCHAR2(30)	NOT NULL,
GH_PSTL_CODE	VARCHAR2(10)	NOT NULL,
GH_ADDR	VARCHAR2(100)	NOT NULL,
GH_DTL_ADDR	VARCHAR2(100)	NOT NULL,
APP_NUM_SEQ	NUMBER(10)	NOT NULL,
JOIN_ID	VARCHAR2(20)	NOT NULL
);

CREATE SEQUENCE GH_NUM_SEQ_NAME
    START WITH 1
    INCREMENT BY 1  
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;

ALTER TABLE Gh ADD CONSTRAINT PK_GH PRIMARY KEY (
GH_NUM_SEQ
);

ALTER TABLE Gh ADD CONSTRAINT FK_TotalApplier_TO_Gh_1 FOREIGN KEY (
APP_NUM_SEQ, JOIN_ID
)
REFERENCES TotalApplier (
APP_NUM_SEQ, JOIN_ID
);
--```

-- instt(TotalApplier와 의존관계)

--```sql
----------------------------- instt -----------------------------
CREATE TABLE Instt (
INSTT_NUM_SEQ	NUMBER(10)	NOT NULL,
INSTT_NAME	VARCHAR2(30)	NOT NULL,
INSTT_OFC_NAME	VARCHAR2(50)	NOT NULL,
INSTT_YEAR	VARCHAR2(20)	NULL,
INSTT_SRTTN	VARCHAR2(1)	NOT NULL,
INSTT_DTL_SRTTN	VARCHAR2(10)	NOT NULL,
INSTT_SOC_NUM	VARCHAR2(20)	NOT NULL,
INSTT_BSNS_NUM	VARCHAR2(30)	NOT NULL,
INSTT_JOB	VARCHAR2(50)	NOT NULL,
INSTT_FAX	VARCHAR2(20)	NOT NULL,
INSTT_HOME_NUM	VARCHAR2(20)	NULL,
INSTT_ACAD_BACK	VARCHAR2(500)	NOT NULL,
INSTT_ACAD_BACK_FILE	VARCHAR2(30)	NOT NULL,
INSTT_CARRER	VARCHAR2(500)	NOT NULL,
INSTT_CARRER_FILE	VARCHAR2(30)	NOT NULL,
INSTT_EMAIL	VARCHAR2(20)	NOT NULL,
INSTT_PHONE_NUM	VARCHAR2(20)	NOT NULL,
INSTT_BANK	VARCHAR2(20)	NOT NULL,
INSTT_ACC_HOL	VARCHAR2(30)	NOT NULL,
INSTT_BANK_NUM	VARCHAR2(30)	NOT NULL,
INSTT_POST_NUM	VARCHAR2(10)	NOT NULL,
INSTT_ADDR	VARCHAR2(50)	NOT NULL,
INSTT_DTL_ADDR	VARCHAR2(50)	NOT NULL,
APP_NUM_SEQ	NUMBER(10)	NOT NULL,
JOIN_ID	VARCHAR2(20)	NOT NULL
);
 
CREATE SEQUENCE INSTT_NUM_SEQ_NAME
    START WITH 1
    INCREMENT BY 1  
    MAXVALUE 1000
    NOCYCLE 
    NOCACHE;
    
ALTER TABLE Instt ADD CONSTRAINT PK_INSTT PRIMARY KEY (
INSTT_NUM_SEQ
);

ALTER TABLE Instt ADD CONSTRAINT FK_TotalApplier_TO_Instt_1 FOREIGN KEY (
APP_NUM_SEQ, JOIN_ID
)
REFERENCES TotalApplier (
APP_NUM_SEQ, JOIN_ID
);

CREATE USER kp identified by OracleTest123;

grant connect, RESOURCE to kp;

commit;

select * from all_users;