ALTER TABLE FAQ ADD FAQ_FILE_LOCA VARCHAR2(300);
ALTER TABLE ANSWER ADD ANS_FILE_LOCA VARCHAR2(300);
ALTER TABLE ANSWER ADD ANS_HIT NUMBER(5) DEFAULT 0 NOT NULL;
ALTER TABLE TOTALAPPLIER ADD APP_NAME VARCHAR2(30) DEFAULT ' ' NOT NULL;

SELECT * FROM FAQ;